
services:
  web-client:
    build:
      context: ./web-client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VOTE_API_BASE_URL=https://vote-api-eh8g.onrender.com
      - PORT=3000
    depends_on:
      - vote-api

  vote-api:
    build:
      context: ./vote-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PG_URL=postgresql://neondb_owner:7VtUji5ALWqJ@ep-dawn-moon-a5pt4aez.us-east-2.aws.neon.tech/neondb?sslmode=require
    


  docs:
    build:
      context: ./docs
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    environment:
      - NODE_ENV=development
    depends_on:
      - vote-api

volumes:
  db_data: